name: Build and deploy .NET Core Function App to Azure functions app
on:
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: DdcPublicAffairsApplicationsKennanAzureFunction
  AZURE_FUNCTIONAPP_PACKAGE_PATH: Ddc.PublicAffairs.Applications.KennanAzureFunction/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: Ddc.PublicAffairs.Applications.KennanAzureFunction
jobs:
  create-azure-resources:
    runs-on: windows-latest
    name: Create resources for Azure function app
    steps:
    - shell: bash
      run: |
        echo $DOTNET_CORE_VERSION
    
